name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff Format
        uses: chartboost/ruff-action@v1
        with:
          args: "format"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-format with Ruff"
          branch: ${{ github.head_ref }}
